# Final frozen comparison

Carica solo artefatti già calcolati. I controlli bloccano confronti con match,
scope, split, seed o protocollo diversi.

In [1]:
import os
from dataclasses import asdict
from pathlib import Path

START_DIRECTORY = Path.cwd().resolve()
if (START_DIRECTORY / "edge_feature_ablation").is_dir():
    PROJECT_ROOT = START_DIRECTORY
elif START_DIRECTORY.name == "experiments":
    PROJECT_ROOT = START_DIRECTORY.parent.parent
else:
    PROJECT_ROOT = START_DIRECTORY.parent

EDGE_DIRECTORY = PROJECT_ROOT / "edge_feature_ablation"
RESULTS_ROOT = PROJECT_ROOT / "results" / "frozen_predictions"

In [2]:
TOURNAMENT_SCOPE = os.environ.get(
    "TENNIS_RUN_SCOPE", "slams_masters"
)
SEED = int(os.environ.get("TENNIS_RUN_SEED", "42"))
OUTPUT_DIRECTORY = RESULTS_ROOT / TOURNAMENT_SCOPE / f"seed_{SEED}"

In [3]:
import sys
sys.path.insert(0, str(EDGE_DIRECTORY))
from experiment_tracking import compare_artifacts

available = sorted(
    path.name.removesuffix(".manifest.json")
    for path in OUTPUT_DIRECTORY.glob("*.manifest.json")
)
print("Available artifacts:", available)

Available artifacts: ['antisymmetric_decoder', 'antisymmetric_mean', 'antisymmetric_mean_tournament', 'antisymmetric_no_direct_bscore', 'antisymmetric_straight_sets', 'antisymmetric_tournament_context', 'bscore_logit', 'bscore_residual', 'current_gnn', 'edge_full', 'edge_match_status', 'edge_set_margin', 'edge_signed_game', 'edge_straight_sets', 'mean_aggregation', 'node_normalization', 'residual_connections', 'tournament_context']

In [4]:
preferred_order = [
    "bscore_logit",
    "current_gnn",
    "edge_signed_game",
    "edge_set_margin",
    "edge_straight_sets",
    "edge_match_status",
    "edge_full",
    "bscore_residual",
    "antisymmetric_decoder",
    "antisymmetric_no_direct_bscore",
    "antisymmetric_straight_sets",
    "antisymmetric_mean",
    "antisymmetric_tournament_context",
    "antisymmetric_mean_tournament",
    "node_normalization",
    "mean_aggregation",
    "residual_connections",
    "tournament_context",
    "full_non_temporal",
]
experiments = [name for name in preferred_order if name in available]
comparison = compare_artifacts(
    OUTPUT_DIRECTORY,
    experiments,
    phase="test",
)
comparison

,n_matches,accuracy,log_loss,brier,delta_vs_current_accuracy,delta_vs_current_log_loss,delta_vs_current_brier
bscore_logit,3770.0,0.644032,0.626188,0.216104,-0.023607,0.014277,0.004639
current_gnn,3770.0,0.667639,0.611911,0.211465,0.000000,0.000000,0.000000
edge_signed_game,3770.0,0.667639,0.610439,0.211110,0.000000,-0.001472,-0.000354
edge_set_margin,3770.0,0.663130,0.609743,0.210854,-0.004509,-0.002168,-0.000610
edge_straight_sets,3770.0,0.665252,0.607425,0.209924,-0.002387,-0.004486,-0.001540
edge_match_status,3770.0,0.659947,0.619680,0.215105,-0.007692,0.007769,0.003641
edge_full,3770.0,0.668966,0.608574,0.210294,0.001326,-0.003337,-0.001170
bscore_residual,3770.0,0.663926,0.612080,0.211545,-0.003714,0.000170,0.000080
antisymmetric_decoder,3770.0,0.671353,0.604410,0.208496,0.003714,-0.007501,-0.002968
antisymmetric_no_direct_bscore,3770.0,0.669496,0.605744,0.209057,0.001857,-0.006167,-0.002408
antisymmetric_straight_sets,3770.0,0.670557,0.607062,0.209690,0.002918,-0.004849,-0.001775
antisymmetric_mean,3770.0,0.664987,0.610437,0.211040,-0.002653,-0.001474,-0.000425
antisymmetric_tournament_context,3770.0,0.664987,0.610556,0.210795,-0.002653,-0.001355,-0.000669
antisymmetric_mean_tournament,3770.0,0.658886,0.615033,0.212905,-0.008753,0.003122,0.001441
node_normalization,3770.0,0.636605,0.678560,0.236828,-0.031034,0.066650,0.025363
mean_aggregation,3770.0,0.658355,0.641350,0.221304,-0.009284,0.029439,0.009840
residual_connections,3770.0,0.648541,0.662737,0.229181,-0.019098,0.050826,0.017717
tournament_context,3770.0,0.660212,0.634438,0.219788,-0.007427,0.022528,0.008324

In [5]:
# Positive is better for accuracy; negative is better for the two losses.
comparison.sort_values("log_loss")

,n_matches,accuracy,log_loss,brier,delta_vs_current_accuracy,delta_vs_current_log_loss,delta_vs_current_brier
antisymmetric_decoder,3770.0,0.671353,0.604410,0.208496,0.003714,-0.007501,-0.002968
antisymmetric_no_direct_bscore,3770.0,0.669496,0.605744,0.209057,0.001857,-0.006167,-0.002408
antisymmetric_straight_sets,3770.0,0.670557,0.607062,0.209690,0.002918,-0.004849,-0.001775
edge_straight_sets,3770.0,0.665252,0.607425,0.209924,-0.002387,-0.004486,-0.001540
edge_full,3770.0,0.668966,0.608574,0.210294,0.001326,-0.003337,-0.001170
edge_set_margin,3770.0,0.663130,0.609743,0.210854,-0.004509,-0.002168,-0.000610
antisymmetric_mean,3770.0,0.664987,0.610437,0.211040,-0.002653,-0.001474,-0.000425
edge_signed_game,3770.0,0.667639,0.610439,0.211110,0.000000,-0.001472,-0.000354
antisymmetric_tournament_context,3770.0,0.664987,0.610556,0.210795,-0.002653,-0.001355,-0.000669
current_gnn,3770.0,0.667639,0.611911,0.211465,0.000000,0.000000,0.000000
bscore_residual,3770.0,0.663926,0.612080,0.211545,-0.003714,0.000170,0.000080
antisymmetric_mean_tournament,3770.0,0.658886,0.615033,0.212905,-0.008753,0.003122,0.001441
edge_match_status,3770.0,0.659947,0.619680,0.215105,-0.007692,0.007769,0.003641
bscore_logit,3770.0,0.644032,0.626188,0.216104,-0.023607,0.014277,0.004639
tournament_context,3770.0,0.660212,0.634438,0.219788,-0.007427,0.022528,0.008324
mean_aggregation,3770.0,0.658355,0.641350,0.221304,-0.009284,0.029439,0.009840
residual_connections,3770.0,0.648541,0.662737,0.229181,-0.019098,0.050826,0.017717
node_normalization,3770.0,0.636605,0.678560,0.236828,-0.031034,0.066650,0.025363